exports.CREATE_DATABASE_SQL = `
  CREATE TABLE IF NOT EXISTS NETWORK
  (
    ID VARCHAR(50) PRIMARY KEY
  );

  INSERT INTO NETWORK
  VALUES ('MAINNET')
  ON CONFLICT
     DO NOTHING;
  INSERT INTO NETWORK
  VALUES ('TESTNET')
  ON CONFLICT
     DO NOTHING;
  INSERT INTO NETWORK
  VALUES ('EDGENET')
  ON CONFLICT
     DO NOTHING;

  CREATE TABLE IF NOT EXISTS KEY_BLOCK
  (
    HASH          VARCHAR PRIMARY KEY,
    HEIGHT        NUMERIC                  NOT NULL,
    MINER         VARCHAR(500)             NOT NULL,
    BENEFICIARY   VARCHAR(500)             NOT NULL,
    NONCE         VARCHAR(200)             NOT NULL,
    PREV_HASH     VARCHAR(200)             NOT NULL,
    PREV_KEY_HASH VARCHAR(200)             NOT NULL,
    STATE_HASH    VARCHAR(200)             NOT NULL,
    TARGET        NUMERIC                  NOT NULL,
    TIME          TIMESTAMP WITH TIME ZONE NOT NULL,
    VERSION       NUMERIC                  NOT NULL,
    NETWORK_ID    VARCHAR(50)              NOT NULL REFERENCES NETWORK (ID) ON DELETE CASCADE
  );
  CREATE TABLE IF NOT EXISTS MICRO_BLOCK
  (
    HASH           VARCHAR(200) PRIMARY KEY,
    KEY_BLOCK_HASH VARCHAR(200)             NOT NULL REFERENCES KEY_BLOCK (HASH) ON DELETE CASCADE,
    HEIGHT         NUMERIC                  NOT NULL,
    POF_HASH       VARCHAR(200)             NOT NULL,
    PREV_HASH      VARCHAR(200)             NOT NULL,
    PREV_KEY_HASH  VARCHAR(200)             NOT NULL,
    SIGNATURE      VARCHAR(200)             NOT NULL,
    TXS_HASH       VARCHAR(200)             NOT NULL,
    TIME           TIMESTAMP WITH TIME ZONE NOT NULL,
    VERSION        NUMERIC                  NOT NULL,
    NETWORK_ID     VARCHAR(50)              NOT NULL REFERENCES NETWORK (ID) ON DELETE CASCADE
  );

  CREATE TABLE IF NOT EXISTS AE_TRANSACTION
  (
    HASH             VARCHAR(200) PRIMARY KEY,
    MICRO_BLOCK_HASH VARCHAR(200) NOT NULL REFERENCES MICRO_BLOCK (HASH) ON DELETE CASCADE,
    BLOCK_HEIGHT     NUMERIC      NOT NULL,
    AMOUNT           NUMERIC      NOT NULL,
    TYPE             VARCHAR(100) NOT NULL,
    FEE              NUMERIC      NOT NULL,
    VERSION          NUMERIC      NOT NULL,
    NONCE            NUMERIC      NOT NULL,
    VM_VERSION       VARCHAR(50),
    GAS              NUMERIC,
    GAS_PRICE        NUMERIC,
    CALL_DATA        VARCHAR,
    CALLER_ID        VARCHAR(200),
    OWNER_ID         VARCHAR(200),
    CONTRACT_ID      VARCHAR(200),
    CODE             VARCHAR,
    DEPOSIT          NUMERIC,
    SENDER_ID        VARCHAR(200),
    RECIPIENT_ID     VARCHAR(200),
    NETWORK_ID       VARCHAR(50)  NOT NULL REFERENCES NETWORK (ID) ON DELETE CASCADE
  );
  CREATE TABLE IF NOT EXISTS TOKEN_EXCHANGE
  (
    EXCHANGE_NAME   VARCHAR(200) PRIMARY KEY,
    MARKET_URL      VARCHAR,
    TARGET_CURRENCY VARCHAR(20)              NOT NULL,
    VOLUME_24       NUMERIC                  NOT NULL,
    PRICE           NUMERIC                  NOT NULL,
    UPDATE_DATE     TIMESTAMP WITH TIME ZONE NOT NULL
  );

  INSERT INTO TOKEN_EXCHANGE
  VALUES ('GATE.IO', 'https://www.gate.io/trade/AE_USDT', 'USDT', 0, 0, current_timestamp)
  ON CONFLICT
     DO NOTHING;
  INSERT INTO TOKEN_EXCHANGE
  VALUES ('Binance', 'https://www.binance.com/en/trade/AE_BTC', 'BTC', 0, 0, current_timestamp)
  ON CONFLICT
     DO NOTHING;
  INSERT INTO TOKEN_EXCHANGE
  VALUES ('Bithumb', 'https://en.bithumb.com/trade/order/AE', 'KRW', 0, 0, current_timestamp)
  ON CONFLICT
     DO NOTHING;
  INSERT INTO TOKEN_EXCHANGE
  VALUES ('Uex', 'https://www.uex.com/tradePro', 'BTC', 0, 0, current_timestamp)
  ON CONFLICT
     DO NOTHING;
`;