export const a = {
  'caller_id': 'ak_6A2vcm1Sz6aqJezkLCssUXcyZTX7X8D5UwbuS2fRJr9KkYpRU',
  'caller_nonce': 1244,
  'contract_id': 'ct_29F3XwwXH8fuEmpgB8VMft4DUuP6oBRNASUa2iCkvSLHGzcrW9',
  'gas_price': 1,
  'gas_used': 319,
  'height': 10841,
  'log': [],
  'return_type': 'ok',
  'return_value': 'cb_Xfbg4g=='
};

export const b =
  {
    'block_hash': 'mh_2T3my2dAQyJbKrRvLfbUZXNnYkzWHoA146vwHwJPjjHfTmktwe',
    'block_height': 10841,
    'hash': 'th_EAwwxTw1LyfyfP4t6RjCYU7WZqrn4RYEBS3iAzJQUPFakjjW4',
    'signatures': ['sg_G4BwJGeyJgLz5wtibVtm48ai1QaEPZMxmN6FRpiHmUAfGxjwFfskyZP1KtiK2176DnNMrAhdwJE2iMcoXhD7WFmjmiDqV'],
    'tx':
      {
        'amount': 1,
        'call_data': 'cb_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACDiIx1s38k5Ft5Ms6mFe/Zc9A/CVvShSYs/fnyYDBmTRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABjIlLH',
        'code': 'cb_+QbYRgGgfGh3S7i5Dvcydfl4s9dyW7oAMzj5s5mMiS0HHnM1rlj5BQ35ASmgDHI5IbWqQ3+nmZ/R5QVAxK01mKyH0tb2r7M/fZBJ7YCDZmFjuMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoP//////////////////////////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD5Aoug4iMdbN/JORbeTLOphXv2XPQPwlb0oUmLP358mAwZk0SEaW5pdLjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKD//////////////////////////////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuQGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQD//////////////////////////////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgP//////////////////////////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD5AVCg//anpRJLtB6eEbVy1G9rBNO9OJkxBJdKnMD6Urlch/2Kc2V0X3dvcmtlcrjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKD//////////////////////////////////////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////////////////////////////////////////+5AaJiAACPYgAAwpGAgIBRfwxyOSG1qkN/p5mf0eUFQMStNZish9LW9q+zP32QSe2AFGIAAY9XUICAUX/iIx1s38k5Ft5Ms6mFe/Zc9A/CVvShSYs/fnyYDBmTRBRiAAEnV1CAUX//9qelEku0Hp4RtXLUb2sE0704mTEEl0qcwPpSuVyH/RRiAAFxV1BgARlRAFtgABlZYCABkIFSYCCQA2AAWZCBUoFSWWAgAZCBUmAgkANgA4FSkFlgAFFZUmAAUmAA81tgAIBSYADzW2AAgRRiAAEfV2AAYABgAGABhANZkIFSWWAgAZCBUmAgkAN/DHI5IbWqQ3+nmZ/R5QVAxK01mKyH0tb2r7M/fZBJ7YCBUmAAYABRUVrxgQJiAAEiVltgAVuQUJBWW2AgAVFRkFCDklCAkVBQgFmQgVJZYCABkIFSYCCQA2AAGVlgIAGQgVJgIJADYABZkIFSgVJZYCABkIFSYCCQA2ADgVKBUpBQkFZbYCABUVFZUICRUFBgAFGBWZCBUpBQYABSWZBQkFZbYCABUVGQUFlQgJFQUGIAAMpWt/rjUA==',
        'deposit': 1,
        'fee': 500000,
        'gas': 1000000,
        'gas_price': 1,
        'nonce': 1244,
        'owner_id': 'ak_6A2vcm1Sz6aqJezkLCssUXcyZTX7X8D5UwbuS2fRJr9KkYpRU',
        'type': 'ContractCreateTx',
        'version': 1,
        'vm_version': '0x01'
      }
  }


export const c = {
  'block_hash': 'mh_2hdp2jdzZozxeGCWJtdyEDm89sPtxYaLTVBMXmcunVbUw3S4kw',
  'block_height': 10938,
  'hash': 'th_2Qi6GKrv9zV9vMh1464ju31wWznrsgwsWAJWg8qbh6M8nrLzTC',
  'signatures': ['sg_MNe7EDqXJ2GDawKkXaUWqdRjjN41mN9FMFiCQTHiRBLkxx1ivH7YPb3AkDwRpzWDTY3Z1i9d4qct9M2PdPJpjERJVi7KT'],
  'tx': {
    'amount': 100000000000000000000,
    'fee': 18080,
    'nonce': 4,
    'payload': '',
    'recipient_id': 'ak_F7B18fnQjDDL8ZFAS3xP7uQyTEBT1fNUtb22JgFZa5hhBtWmT',
    'sender_id': 'ak_RWHjQauttzSqs2EripNCbZyEKLpAQyyjPUBmR3a5aZvkz3Wzp',
    'type': 'SpendTx',
    'version': 1
  }
}